// Generated by scripts/embedded-assets.ts — do not edit.
// This committed stub keeps tsc and source-mode runs working before prepack
// regenerates the module with the staged asset contents. The file is
// gitignored, so regenerations never appear as changes.
export const BUILD_ID = "stub";
export const EMBEDDED_ASSETS: Record<string, string> = {};
