import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

export const EMBEDDED_ASSETS_STUB = `// Generated by scripts/embedded-assets.ts — do not edit.
// This committed stub keeps tsc and source-mode runs working before prepack
// regenerates the module with the staged asset contents. The file is
// gitignored, so regenerations never appear as changes.
export const BUILD_ID = "stub";
export const EMBEDDED_ASSETS: Record<string, string> = {};
`;

/**
 * Emit a TypeScript module containing every staged asset's contents as string
 * literals. A compiled standalone binary bundles this module, so the binary
 * carries its assets inside the executable; at runtime the CLI materializes
 * them to a real cache directory when Docker needs files on disk.
 */
export async function generateEmbeddedAssetsModule(
  assetsRoot: string,
  outputPath: string,
): Promise<void> {
  const files: string[] = [];
  async function walk(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const fullPath = join(directory, entry.name);
      if (entry.isDirectory()) {
        await walk(fullPath);
      } else if (entry.isFile()) {
        files.push(relative(assetsRoot, fullPath));
      }
    }
  }
  await walk(assetsRoot);
  files.sort();

  const entries: string[] = [];
  for (const assetPath of files) {
    const content = await readFile(join(assetsRoot, assetPath), "utf8");
    entries.push(`${JSON.stringify(assetPath)}: ${JSON.stringify(content)}`);
  }

  // Content-derived, not a timestamp: the cache key must change when and only
  // when the assets do. A random or time-based id also invalidates correctly,
  // but it cannot distinguish "same assets, rebuilt binary" from "stale
  // cache", and the stub build id ("stub") is shared by every source-mode run,
  // so a cache written by one is silently reused by the next.
  const digest = new Bun.CryptoHasher("sha256");
  for (const entry of entries) digest.update(entry);
  const buildId = digest.digest("hex").slice(0, 32);
  const moduleSource = [
    "// Generated by scripts/embedded-assets.ts — do not edit.",
    `export const BUILD_ID = ${JSON.stringify(buildId)};`,
    `export const EMBEDDED_ASSETS: Record<string, string> = {`,
    ...entries.map((entry) => `  ${entry},`),
    "};",
    "",
  ].join("\n");

  await writeFile(outputPath, moduleSource);
}

if (import.meta.main) {
  const scriptPath = fileURLToPath(import.meta.url);
  const packageRoot = join(dirname(scriptPath), "..");
  await generateEmbeddedAssetsModule(
    join(packageRoot, "assets"),
    join(packageRoot, "src", "embedded-assets.generated.ts"),
  );
}
